### ISSUE TITLE
OpenIdToken ParseOpenIdToken(), property oid always empty, causing exception

### ISSUE THREAD

**Issue by RobDaPraia** [jasonjoh/dotnet-outlook-nosdk#3]
Thanks for this great example.

Running this code I noticed that in the method OpenIdToken.ParseOpenIdToken(string id_token) the oid never gets filled with a value, causing exception in the TokenCache since the value is null.

Could it be that in the received jwt token there is no longer a user id?

**Comment by jasonjoh** [comment]
Ah yes, good catch. In order for the token to include the `oid`, you have to request the `profile` scope. Patch incoming.
